### ISSUE TITLE
Bold text for unread posts in threads

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#26]
span class="subject_old" and "subject_new" are added (CSS class), anyway it always add subject_old css class for the thread title, any solution? @dragonexpert

**Comment by Eldenroot** [comment]
It is weird, sometimes the post subject is bold, sometimes not... even with unread posts...

**Comment by dragonexpert** [comment]
I'm not sure.   Line 188 of inc/plugins/recentthreads/hooks.php is where the conditional is, but I'm not sure what is wrong.
