### ISSUE TITLE
Moved thread - duplication in recent thread box

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#27]
The bug which was fixed is back... when you moved a thread, it is shows twice (latest v15 from GitHub)

![bug](https://user-images.githubusercontent.com/778890/28531723-ef7f640e-7097-11e7-8e7d-0416f67882a5.png)

`if(strpos($thread['closed'], "moved|") === 0)
{
$thread['tid'] = substr($thread['closed'], 6);
}`

around line 400

@dragonexpert

**Comment by dragonexpert** [comment]
Fixed in the new update.
