### ISSUE TITLE
Add support for template variable - show thread start (created) time and date 

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#28]
Something like this:
https://community.mybb.com/thread-126926-post-918776.html#pid918776

@dragonexpert

**Comment by dragonexpert** [comment]
Probably easy to implement.  I want to know about the issue with formatting the author username before I do a commit that adds this.

**Comment by Eldenroot** [comment]
I replied to your post... about this issue, for MyBB threads I use this code:
https://community.mybb.com/thread-126926-post-918776.html#pid918776

**Comment by dragonexpert** [comment]
I'll make it a language variable so it can be translated.

**Comment by dragonexpert** [comment]
Done.  I also added an update script, however the update script will not touch templates.  Use {$create_string} if you want Created on date x at time y.  Otherwise can use {$create_date} and {$create_time} individually.  Please note that {$create_string} relies on a language variable.
