### ISSUE TITLE
Add setting - use usergroup style

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#29]
Add setting - use usergroup style - I mean format username output according to the usergroup style

**Comment by dragonexpert** [comment]
Is this version automatically formatting the username for you?  If not, I'll need to look at the recentthread_thread template.  I'm using {$thread['author']} to display it.

**Comment by Eldenroot** [comment]
Yes, it works but there should be settings for that - use usergroup styles or not

**Comment by dragonexpert** [comment]
Might as well do the same for last poster while I'm at it.

**Comment by dragonexpert** [comment]
Done
