### ISSUE TITLE
Possibility to show Forum and Subforum?

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#38]
I would like to ask you if is possible to show something like "Forum 1 -> Subforum". Now it displays only forum where the thread is posted. Something like "breadcrumb".

It is sometimes not really useful if you have 2 or more forums with same name, so the thread have same forum displayed even when they are in two different places.

Sorry for my English, really difficult to describe this feature request.

**Comment by dragonexpert** [comment]
I think I know what you mean.  It will have to wait until tomorrow though to do.  I'll give you a private link when I do this to see if it is what you meant.

**Comment by dragonexpert** [comment]
Done.  You'll need to deactivate and reactivate though to also make sure templates are current.

**Comment by Eldenroot** [comment]
Thank you, I will try ASAP.

**Comment by Eldenroot** [comment]
Works fine, anyway can you add settings for maximum length? Or show only last 2, not the whole path? Thank you!

EDIT: If you disable "Use breadcrumbs for forum name" -> no forum name is displayed :(

**Comment by dragonexpert** [comment]
[quote]If you disable "Use breadcrumbs for forum name" -> no forum name is displayed[/quote]  Not a bug.  This is intentional.  Might be tough only doing a partial path.

**Comment by Eldenroot** [comment]
@dragonexpert - yes, I agree... partial path or full path settings

**Comment by dragonexpert** [comment]
Completed.
