### ISSUE TITLE
ACP improvements

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#40]
- Add PayPal image instead of link to the right side
- add a link to plugin configuration into plugin page
- hide "run update script" if there is no need to run it

**Comment by dragonexpert** [comment]
1) Can do in the future.
2) Can't do because you won't know what the id of the setting group is.
3) The problem is it depends on what version a person had previously and it would take multiple queries to attempt to check everything.  If there is no need, it doesn't do anything.
