### ISSUE TITLE
Moved threads are displayed as unread all the times

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#43]
When you move a thread (I moved a thred from subcategory into subsubcategory) -> recent thread plugin display the thread title bolded all the time (unread posts) even I read it. Can you reproduce this issue please?

**Comment by Eldenroot** [comment]
BUMP

**Comment by Eldenroot** [comment]
BUMP :(

**Comment by dragonexpert** [comment]
Is this fixed from the pull request #49 ?

**Comment by Eldenroot** [comment]
Yes, this is fixed :) one issue less
