### ISSUE TITLE
Is it correct?

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#44]
https://github.com/dragonexpert/recentthreads/blob/76d915b544c4f3539942316e79910a1424146077/inc/plugins/recentthreads/templates.php#L12

**Comment by dragonexpert** [comment]
Should be.  Template Groups use \<lang:variable\> for the name of the group.

**Comment by Eldenroot** [comment]
I opened this issue because I have a small problem with not displaying the name of the recenthread template group in Fastyle plugin (others plugins are displayed). 

![image](https://user-images.githubusercontent.com/778890/37926149-da74eca4-3136-11e8-9995-074d1e1c71bd.png)

**Comment by dragonexpert** [comment]
Does it work without using FAStyle?

**Comment by Eldenroot** [comment]
Yes it works... it works in Fastyle too, but you the name of the template group is not displayed (only for recentthread plugin, other plugins template groups are displayed correctly).

It is a small issue, I need to solve somehow #43
