### ISSUE TITLE
All threads are displayed as unread (bold text)

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#45]
Hi, I use your latest GitHub version... unfortunately all threads in recent box are displayed as unread even there is no unread message. It has all the time "unread" css. Is possible to check the code if it is not bugged? Thank you very much

@dragonexpert

**Comment by Eldenroot** [comment]
@dragonexpert - I am glad, that there is no XSS vulnerability... anyway can you please check this? I can provide you a testing account on my board to track down this issue. Thank you in advance!

**Comment by dragonexpert** [comment]
It will most likely be a few days as I have a lot going on this weekend.  I"m also having a bit of an issue working on setting up an environment to test stuff again.

**Comment by Eldenroot** [comment]
@dragonexpert - I can provide you a test account with ftp access. Is there any way how to help you to debug and fix this? Thank you!!!

**Comment by Eldenroot** [comment]
I can set for you a testing board... please I would like to kinldy ask you for help :(

**Comment by Eldenroot** [comment]
Happens on my fresh install too :(
php 7.1
