### ISSUE TITLE
Vulnerability XSS

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#46]
as reported on MyBB extend site, can you please fix it? This plugin is really useful and is used by a lot of users, should get a security update ASAP.

@dragonexpert

**Comment by dragonexpert** [comment]
I posted in a private thread I made in private inquiries.  Either they tell me the steps to reproduce it or I demanded that it be untagged as vulnerable.

**Comment by dragonexpert** [comment]
It has been unmarked as vulnerable.
