### ISSUE TITLE
php error ACP plugin page

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#48]
![image](https://user-images.githubusercontent.com/778890/52302369-436f3580-298d-11e9-89c3-fedc70abeb5b.png)

**Comment by dragonexpert** [comment]
I don't have a test site ready yet, but go to the end of line 7 of inc/plugins/recentthread.php.  Line 8 use this: var_dump($my_plugins);  Line 9 put this: die();  This will stop script execution at that point.  It may be that the structure of the plugin cache changed from when I last updated.  Let me know what it says.

**Comment by Eldenroot** [comment]
There is no error message on php 7.1, so I will test tommorow again on the older test board where I run php 5.6.x and let you know. Thank you for your reply!

**Comment by dragonexpert** [comment]
There shouldn't be an error if you modified it, but it should say array and a bunch of values which is what I need.

**Comment by dragonexpert** [comment]
I set up a test environment that currently has 7.3.1 for php version.  I get no errors when I used the code that is currently on Github.

**Comment by dragonexpert** [comment]
So I just switched to PHP 5.6 and it still doesn't show an error for me.  I also tried using Deactivate so my plugin cache would be empty and don't get the error.

**Comment by Eldenroot** [comment]
I cannot reproduce it again (tested again with php 5.6.x). I am closing this one :(
