### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#5]
Users without permissions to see some forums can see threads in recent thread table on index page...

more info: http://community.mybb.com/thread-159857-page-5.html

**Comment by dragonexpert** [comment]
IF you make sure they don't have the Can Search Forum permission it is blocked.

**Comment by Eldenroot** [comment]
OK, I will check. Thx

**Comment by dragonexpert** [comment]
Easy query for you:
UPDATE mybb_forumpermissions SET cansearch=0 WHERE canview=0;

Then rebuild the forum permission cache.

**Comment by Eldenroot** [comment]
it would be better to check "can view" than can search, not?

**Comment by dragonexpert** [comment]
I'll consider it in the next release.  When I assign permissions, if a group can't view the forum, I also make sure they can't search it.

**Comment by Eldenroot** [comment]
Yes, I understand. I have changed permissions and now it looks fine. Thx

**Comment by Eldenroot** [comment]
OK, my issue is still here. I have double checked my setting for these "hidden" forums - all groups have disabled (unchecked) "Can search forum" and "Can view forum" and "Can Can view threads..."

but they can see these threads in recent threads table on index. There must by something wrong

**Comment by dragonexpert** [comment]
I'll look into it when I have more time.  For a temporary fix, try putting the forums you don't want anyone but staff to see in the Forums To Ignore setting.

**Comment by Eldenroot** [comment]
Thank you!

**Comment by dragonexpert** [comment]
I'm guessing the core function get_unsearchable_forums probably has a permission error somewhere since that should in theory get forums that have cansearch permission 0.

**Comment by dragonexpert** [comment]
Seems like the code should be checking against both cansearch and canview.
[code]if($perms['canview'] != 1 || $perms['cansearch'] != 1 || $pwverified == 0 || $forum['active'] == 0)
        {
            if($unsearchableforums)
            {
                $unsearchableforums .= ",";
            }
            $unsearchableforums .= "'{$forum['fid']}'";
        }
    }
    $unsearchable = $unsearchableforums;[/code]

**Comment by Eldenroot** [comment]
would be better to check only one - can search

**Comment by dragonexpert** [comment]
$forum['active'] refers to if a forum has the Forum Is Active checked.  If you want to try and tackle this, get_unsearchable_forums is in inc/functions_search.php

**Comment by Eldenroot** [comment]
I am sorry but I dont know how :( morevoer I am not at home so I dont have a FTP access to my server

**Comment by Eldenroot** [comment]
So issues persists... more info on forum. Maybe you cas take some ideas from recent thread mod for mybb 1.6. It is working fine (even on 1.8)

EDIT: What about to check only can view a thread?
