### ISSUE TITLE
Add new option - disable AJAX refreshing (or allow only for selected usergroups)

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#51]

**Comment by dragonexpert** [comment]
I think it would be best to either be ajax or no ajax.  Due to the way forum permissions are handled, it will refresh once basically immediately to make sure permissions are done correctly.

**Comment by Eldenroot** [comment]
Yes, I agree. This is implemented in DVZ Shoutbox plugin - you can enable/disable ajax refreshing and enable it only for specific usergroups.

**Comment by dragonexpert** [comment]
We can look at doing that in the next build.  I want to push the current build since there isn't issues that I am aware of.

**Comment by Eldenroot** [comment]
Ok, agree. Thx

**Comment by dragonexpert** [comment]
I think just an all or nothing is how I want to do this.  If someone wants to actually program a per usergroup and it works, by all means, submit a pull request.  For now, I am going to say to just comment out the line var refresher = window.setInterval(function () {refresh_recent_threads()}, 30000) in the recentthread_headerinclude template if you don't want refreshing.
