### ISSUE TITLE
Support FontAwesome in thread icons?

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#55]
Hi @dragonexpert - I use FontAwesome icons for my thread icons... is possible to use them in recentthread plugin as well?

I use this tutorial - the images are just replaced by fontawesome icons
https://community.mybb.com/thread-220598.html

**Comment by dragonexpert** [comment]
I'll look into it next week.  Have finals I'm working on right now.

**Comment by dragonexpert** [comment]
It would be a lot of work, but should still be able to be supported, but you would have to make lots of code changes for everything to be consistent.

**Comment by dragonexpert** [comment]
@Eldenroot Can you test the new inc/plugins/hooks.php file for branch 20?

**Comment by Eldenroot** [comment]
Sure, I will, but not today, probably tomorrow after work, I will let you know :)

**Comment by Eldenroot** [comment]
Works fine in v20 pre-release! Thank you!

![image](https://user-images.githubusercontent.com/778890/104354233-35c37280-5509-11eb-8038-90da49da839a.png)
