### ISSUE TITLE
Does not show the template "recentthread_last_avatar" if you are a guest

### ISSUE THREAD

**Issue by Maria22s** [dragonexpert/recentthreads#59]
Hello happy new year, there is a problem with your plugin. When you are invited it does not show "recentthread_last_avatar" it is empty, I do not know why it happens.

But if you are registered in the forum if it shows the template "recentthread_last_avatar"

When you are a registered user.
![image](https://user-images.githubusercontent.com/53314750/103703376-d4862700-4f7d-11eb-9696-981804171b74.png)

When you are a guest
![image](https://user-images.githubusercontent.com/53314750/103703492-ff707b00-4f7d-11eb-8112-0115ba75a83a.png)

I made modifications to the templates to improve their appearance. So use the default templates to test if it was that and no, it's the same!
Thanks for your help friend!

**Comment by dragonexpert** [comment]
Do guests have permission to view avatars?  [Relevant Code](https://github.com/dragonexpert/recentthreads/blob/master/inc/plugins/recentthreads/hooks.php#L362)

**Comment by Maria22s** [comment]
Guest permissions are by default. I don't know that I can be a friend.

**Comment by Maria22s** [comment]
I tried a fresh installation on my localhost and it's the same!

**Comment by dragonexpert** [comment]
I'll have to look into it.

**Comment by dragonexpert** [comment]
So after looking into this, it seems that guests do not ever get the permission for viewing avatars in posts.  It is considered a User CP option.  I don't force avatars to be displayed because some people might be viewing a forum using data or may be on a limited connection.  If you absolutely want it on your forum, you would have to get rid of the && $mybb->user['showavatars'] part.

**Comment by Maria22s** [comment]
I did it and it worked wonderfully, Thanks friend you can close the thread. I should add an option for that it would be great, Greetings and thanks again
