### ISSUE TITLE
Make misc.php_action=recent_threads More Known

### ISSUE THREAD

**Issue by dragonexpert** [dragonexpert/recentthreads#67]
I'm thinking of having a hover function on the ~ Recent Threads ~ part to make it more obvious that it exists.  Additionally, the templates for that page should be renamed to start with recentthreads so it becomes easier to automate maintenance and upgrade scripts.

**Comment by Eldenroot** [comment]
Good idea!

**Comment by dragonexpert** [comment]
This is done.
