### ISSUE TITLE
Who posted is not working in post column

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#71]
![image](https://user-images.githubusercontent.com/778890/104354164-1a586780-5509-11eb-83f6-bcab6b05409e.png)

It should be a link and clickable, right? Now it is clickable but nothing happens.

**Comment by Eldenroot** [comment]
After click you get this error below the box

![image](https://user-images.githubusercontent.com/778890/104356220-f8acaf80-550b-11eb-977e-b65a05f46644.png)

**Comment by dragonexpert** [comment]
Edit template recentthread_misc_mod_column to be this:  
`<td class="{$trow}"><input type="checkbox" name="tid{$thread['tid']}" value="{$thread['tid']}" id="tid{$thread['tid']}" class="thread_checkbox" onclick="update_tidlist({$thread['tid']})" /></td>`

I will try and update the templates.json file to reflect this change.

**Comment by dragonexpert** [comment]
Updated templates.json on my local files.  Looking at the other issues in case there are other template problems and this way everything can be fixed at one time without doing a separate commit for each.

**Comment by dragonexpert** [comment]
This is fixed now.
